openapi: 3.0.0
info:
  version: 1.0.0
  title: E - Commerce
  description: E - Commerce Server
  license:
    name: seongikCho
servers:
  - url: 'http://localhost:4444/'
components:
  parameters:
    productId:
      name: id
      in: path
      description: 제품 번호
      required: true
      schema:
        type: string
    orderId:
      name: id
      in: path
      description: 주문 번호
      required: true
      schema:
        type: string
  securitySchemes:
    jwt:
      type: apiKey
      in: header
      name: Authorization
      description: JWT 토큰
  schemas:
    product:
      properties:
        name:
          type: string
          description: 제품 이름
          example: MagSafe형 iPhone 14 실리콘 케이스 - 카나리 옐로
        price:
          type: number
          desc: 제품 가격
          example: 69000
        description:
          type: string
          description: 제품 정보
          example: Apple이 디자인한 이 MagSafe형 실리콘 케이스는 iPhone 14에 멋을 한층 더하는 동시에 폰을 든든하게 보호해줍니다.
    reply:
      properties:
        memo:
          type: string
          description: 제품에 대한 후기
          example: 저렴하게 잘 샀습니다. 다음에 또 주문할게요.
    order:
      properties:
        product:
          type: product
          description: 주문명
          example: 645df5e5278345f7b7f21e65
        quantity:
          type: number
          description: 주문 수량
          example: 1
        user:
          type: user
          description: 구매자
          example: 64429ec62ea5616cfe5fe437
    user:
      properties:
        email:
          type: string
          description: 이메일 주소
          required: true
          example: imlogic20@gmail.com
        password:
          type: string
          description: 비밀번호
          required: true
          example: asdf1234!@#$
        username:
          type: string
          description: 유저 닉네임
          example: seongik
        phoneNumber:
          type: number
          description: 휴대폰 번호
          required: true
          example: 01012347890
        birth:
          type: date
          description: 생년월일
          example: 19930201
        role:
          type: string
          description: 사용자 권한
          example: user / admin
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  examples:
    getAllProducts:
      value:
        message: successfully get all products from Redis
        products:
          - product_id: 645c6e83b9e1ccb37c920ae7
            name: iPad Pro 11
            price: 1390000
            description: |-
              프로급 워크플로를 위한 막강한 성능과 온종일 가는 배터리 사용 시간을 구현하는 Apple M2 칩¹
              ProMotion, True Tone, P3의 넓은 색영역을 갖춘 27.9cm Liquid Retina 디스플레이각주²
              LiDAR 스캐너를 탑재한 프로급 카메라, 센터 스테이지 기술이 적용된 울트라 와이드 전면 카메라
              가장 빠른 Wi-Fi 연결성을 선사하는 Wi-Fi 6E 그리고 초고속 다운로드 및 고화질 스트리밍이 가능한 5G.³
              Apple Pencil(2세대),Magic Keyboard, Smart Keyboard Folio과 호환각주⁴
          - product_id: 645b337dc24ebe7016fd2dfd
            name: Apple Watch Ultra
            price: 1149000
            description: '동작 버튼을 갖추고 있으며 무게감, 견고함, 내부식성이 완벽한 조화를 이루는 초강력 49mm 티타늄 케이스 혹독한 조건에서도 보기 쉬운 역대 가장 크고 밝은 상시표시형 Retina 디스플레이 거리, 페이스, 이동 경로를 계산할 수 있도록 정확한 위치 정보를 제공하는 정밀한 이중 주파수 GPS 최대 36시간의¹ 배터리 사용 시간, 그리고 저전력 모드에서 최대 60시간²'
    getProduct:
      value:
        message: successfully get product from DB
        product:
          _id: 645c6e83b9e1ccb37c920ae7
          name: iPad Pro 11
          price: 1390000
          desc: |-
            프로급 워크플로를 위한 막강한 성능과 온종일 가는 배터리 사용 시간을 구현하는 Apple M2 칩¹
            ProMotion, True Tone, P3의 넓은 색영역을 갖춘 27.9cm Liquid Retina 디스플레이각주²
            LiDAR 스캐너를 탑재한 프로급 카메라, 센터 스테이지 기술이 적용된 울트라 와이드 전면 카메라
            가장 빠른 Wi-Fi 연결성을 선사하는 Wi-Fi 6E 그리고 초고속 다운로드 및 고화질 스트리밍이 가능한 5G.³
            Apple Pencil(2세대),Magic Keyboard, Smart Keyboard Folio과 호환각주⁴
          createdAt: '2023-05-11T04:26:44.005Z'
          updatedAt: '2023-05-11T04:26:44.005Z'
          __v: 0
    createProduct:
      value:
        message: successfully created new product
        product:
          name: 45mm 브라이트 오렌지 스포츠 밴드
          price: 65000
          desc: 스포츠 밴드는 특수 제작한 고탄성 불화탄성중합체로 만들어 튼튼하고 내구성이 뛰어나면서도 놀라우리만치 부드럽습니다. 부드러운 고밀도 소재의 밴드가 우아하게 손목을 감싸주어 피부에 닿는 느낌이 편안합니다. 또한 혁신적인 핀앤턱 잠금장치는 깔끔하게 떨어지는 착용감을 선사합니다.
          _id: 645dccb7c4bffbf15f95c54c
          createdAt: '2023-05-12T05:20:55.480Z'
          updatedAt: '2023-05-12T05:20:55.480Z'
          __v: 0
    updateProduct:
      value:
        msg: successfully updated product by 645b337dc24ebe7016fd2dfd
        product:
          _id: 645b337dc24ebe7016fd2dfd
          name: test11111111111111111111111111111111
          price: 1231231241241
          desc: test11111111111111111111111111111111
          createdAt: '2023-05-10T06:02:37.034Z'
          updatedAt: '2023-05-12T04:16:43.624Z'
          __v: 0
    deleteAllProducts:
      value:
        message: successfully deleted all data in DB & Redis
    deleteProduct:
      value:
        message: successfully deleted data by 645dea5be6b8f6d7c770f3bf
    createReplyToProduct:
      value:
        message: successfully created new reply
        reply:
          user: 64429ec62ea5616cfe5fe437
          memo: 저렴하게 잘 샀습니다. 다음에 또 주문할게요.
          reply_id: 645df643278345f7b7f21e6d
    getAllOrders:
      value:
        message: successfully get all orders from DB
        orders:
          - _id: 6461a63408373afc9748814e
            product:
              _id: 645df5e5278345f7b7f21e65
              name: 45mm 브라이트 오렌지 스포츠 밴드
              price: 65000
            quantity: 1
            user:
              _id: 64429ec62ea5616cfe5fe437
              email: imlogic20@gmail.com
              username: imlogic20
              phoneNumber: 1095627719
            __v: 0
    getOrder:
      value:
        message: successfully get order by 6461a63408373afc9748814e from DB
        order:
          _id: 6461a63408373afc9748814e
          product:
            _id: 645df5e5278345f7b7f21e65
            name: 45mm 브라이트 오렌지 스포츠 밴드
            price: 65000
            desc: 스포츠 밴드는 특수 제작한 고탄성 불화탄성중합체로 만들어 튼튼하고 내구성이 뛰어나면서도 놀라우리만치 부드럽습니다. 부드러운 고밀도 소재의 밴드가 우아하게 손목을 감싸주어 피부에 닿는 느낌이 편안합니다. 또한 혁신적인 핀앤턱 잠금장치는 깔끔하게 떨어지는 착용감을 선사합니다.
          quantity: 1
          user:
            _id: 64429ec62ea5616cfe5fe437
            email: imlogic20@gmail.com
            password: $2b$10$MmLsSwKzVgnYeccAUOH6Q.ftj1gqKzp3H/y2B25SY.vwaD6AISB6K
            username: imlogic20
            phoneNumber: 1095627719
            role: admin
            isEmailConfirm: false
            createdAt: '2023-04-21T14:33:42.503Z'
            updatedAt: '2023-04-21T14:33:42.503Z'
            profileImg: 'https://s.gravatar.com/avatar/8514e2835b97194ffe16b21bf723e420?s=200&r=pg&d=mm'
            __v: 0
          __v: 0
    createOrder:
      value:
        message: successfully created new order
        order:
          product: 645df5e5278345f7b7f21e65
          quantity: 1
          user: 64429ec62ea5616cfe5fe437
          _id: 6461afeea43a7cb2ea7e966a
          __v: 0
    updateOrder:
      value:
        message: successfully updated data by 6461a63408373afc9748814e
    deleteAllOrders:
      value:
        message: successfully deleted all Orders
    deleteOrder:
      value:
        message: successfully deleted data by 6461beeeace9cd8297757759
    getProfile:
      value:
        message: successfully get userInfo
        user:
          _id: 64429ec62ea5616cfe5fe437
          email: imlogic20@gmail.com
          password: $2b$10$MmLsSwKzVgnYeccAUOH6Q.ftj1gqKzp3H/y2B25SY.vwaD6AISB6K
          username: imlogic20
          phoneNumber: 1095627719
          role: admin
          isEmailConfirm: false
          createdAt: '2023-04-21T14:33:42.503Z'
          updatedAt: '2023-04-21T14:33:42.503Z'
          profileImg: 'https://s.gravatar.com/avatar/8514e2835b97194ffe16b21bf723e420?s=200&r=pg&d=mm'
          __v: 0
    getAllUsers:
      value:
        message: successful get all users from DB
        users:
          - _id: 64429ec62ea5616cfe5fe437
            email: imlogic20@gmail.com
            password: $2b$10$MmLsSwKzVgnYeccAUOH6Q.ftj1gqKzp3H/y2B25SY.vwaD6AISB6K
            username: imlogic20
            phoneNumber: 1095627719
            role: admin
            isEmailConfirm: false
            createdAt: '2023-04-21T14:33:42.503Z'
            updatedAt: '2023-04-21T14:33:42.503Z'
            profileImg: 'https://s.gravatar.com/avatar/8514e2835b97194ffe16b21bf723e420?s=200&r=pg&d=mm'
            __v: 0
          - _id: 644357525c9f7581c747eb06
            email: imlogic@naver.com
            password: $2b$10$kgbsn3vRiewjipcLCkdKsexLtNrtMhnCENRcfge6R77Ar20CJ4MNa
            username: imlogic
            phoneNumber: 1095627719
            role: admin
            isEmailConfirm: false
            createdAt: '2023-04-22T03:41:06.923Z'
            updatedAt: '2023-04-22T03:41:06.923Z'
            profileImg: 'https://s.gravatar.com/avatar/97d4e35bcd645ff51cc8fc74dbe752dc?s=200&r=pg&d=mm'
            __v: 0
  responses:
    successResponse:
      description: successful request with no data
      content:
        application/json:
          schema:
            type: object
            example:
              status: 200
              success: true
              message: message
    BadRequest:
      description: 400
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    Unauthorized:
      description: 401
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 인증되지 않음
    Forbidden:
      description: 403
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 접근 금지
    Not found:
      description: 404
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 찾을 수 없음
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
paths:
  /product:
    get:
      tags:
        - Product
      summary: 등록된 모든 제품 조회 - 관리자
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                products:
                  $ref: '#/components/examples/getAllProducts'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Product
      summary: 판매 제품 등록 - 판매자
      consumes:
        - application/json
      produces:
        - application/json
      security:
        - $ref: '#/components/securitySchemes/jwt'
      requestBody:
        x-name: body
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                productExample:
                  $ref: '#/components/examples/getProduct'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Product
      summary: 등록된 모든 제품 삭제 - 판매자
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                deleteAllProducts:
                  $ref: '#/components/examples/deleteAllProducts'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/product/{id}':
    get:
      tags:
        - Product
      summary: 제품의 상세 페이지 이동 - 모든 사용자
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/productId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                product:
                  $ref: '#/components/examples/getProduct'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Product
      summary: 등록한 판매 제품 수정 - 판매자
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/productId'
      requestBody:
        x-name: body
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                product:
                  $ref: '#/components/examples/updateProduct'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Product
      summary: 특정 제품 삭제 - 판매자
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/productId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              examples:
                deleteAllProducts:
                  $ref: '#/components/examples/deleteProduct'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Product
      summary: 후기 작성 - 모든 사용자
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/productId'
      requestBody:
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/reply'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reply'
              examples:
                deleteAllProducts:
                  $ref: '#/components/examples/createReplyToProduct'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /order:
    get:
      tags:
        - Order
      summary: 장바구니에 담긴 모든 주문 조회 - 고객
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/getAllOrders'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Order
      summary: 장바구니 등록
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        x-name: body
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/order'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/createOrder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Order
      summary: 장바구니에 등록된 모든 주문 삭제
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/deleteAllOrders'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/order/{id}':
    get:
      tags:
        - Order
      summary: 상세 주문조회
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/orderId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/getOrder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - Order
      summary: 주문 수량 수정
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/orderId'
      requestBody:
        x-name: body
        required: true
        content:
          x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/order'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/updateOrder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Order
      summary: 특정 주문 삭제
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/components/parameters/orderId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
              examples:
                order:
                  $ref: '#/components/examples/deleteOrder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /user:
    get:
      tags:
        - User
      summary: 프로필 정보 가져오기
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                user:
                  $ref: '#/components/examples/getProfile'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /user/list:
    get:
      tags:
        - User
      summary: 모든 유저 프로필 조회
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
              examples:
                user:
                  $ref: '#/components/examples/getAllUsers'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
